name: Node.js Package

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:  
    - uses: actions/checkout@v2  
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: 'https://npm.registry.cheetah.games'   
    - run: sed -i.bak 's/999.999.999/${{ github.event.release.tag_name }}/' Packages/games.cheetah.play-games/package.json
    - run: rm -f Unity/Packages/games.cheetah.play-games/package.json.bak
    - run: npm publish Packages/games.cheetah.play-games --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.TOKEN_REPOSITORY_CHEETAH_GAMES}}
